pdf: ../pdf/A.pdf

../pdf/A.pdf: A.tex sections
	mkdir -p ../pdf
	pdflatex -output-directory=../pdf/ A.tex
	rm ../pdf/A.pdf
	pdflatex -output-directory=../pdf/ A.tex
	pdflatex -output-directory=../pdf/ Selected.tex
	rm ../pdf/Selected.pdf
	pdflatex -output-directory=../pdf/ Selected.tex